USE [master]
GO
/****** Object:  Database [evolent]    Script Date: 04/21/2018 15:18:19 ******/
CREATE DATABASE [evolent] ON  PRIMARY 
( NAME = N'evolent', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\evolent.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'evolent_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\evolent_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [evolent] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [evolent].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [evolent] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [evolent] SET ANSI_NULLS OFF
GO
ALTER DATABASE [evolent] SET ANSI_PADDING OFF
GO
ALTER DATABASE [evolent] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [evolent] SET ARITHABORT OFF
GO
ALTER DATABASE [evolent] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [evolent] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [evolent] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [evolent] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [evolent] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [evolent] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [evolent] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [evolent] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [evolent] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [evolent] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [evolent] SET  DISABLE_BROKER
GO
ALTER DATABASE [evolent] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [evolent] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [evolent] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [evolent] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [evolent] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [evolent] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [evolent] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [evolent] SET  READ_WRITE
GO
ALTER DATABASE [evolent] SET RECOVERY SIMPLE
GO
ALTER DATABASE [evolent] SET  MULTI_USER
GO
ALTER DATABASE [evolent] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [evolent] SET DB_CHAINING OFF
GO
USE [evolent]
GO
/****** Object:  Table [dbo].[Contact]    Script Date: 04/21/2018 15:18:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contact](
	[ContactId] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](256) NULL,
	[LastName] [nvarchar](256) NULL,
	[Email] [nvarchar](256) NULL,
	[PhoneNumber] [nvarchar](16) NULL,
	[IsActive] [bit] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_Contact] PRIMARY KEY CLUSTERED 
(
	[ContactId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Default [DF_Contact_IsActive]    Script Date: 04/21/2018 15:18:21 ******/
ALTER TABLE [dbo].[Contact] ADD  CONSTRAINT [DF_Contact_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO
/****** Object:  Default [DF_Contact_IsDeleted]    Script Date: 04/21/2018 15:18:21 ******/
ALTER TABLE [dbo].[Contact] ADD  CONSTRAINT [DF_Contact_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO

SET IDENTITY_INSERT [dbo].[Contact] ON
INSERT [dbo].[Contact] ([ContactId], [FirstName], [LastName], [Email], [PhoneNumber], [IsActive], [IsDeleted]) 
VALUES (1, N'Ajay', N'G', N'ajay@gmail.com', N'1234567990', 0, 0)
SET IDENTITY_INSERT [dbo].[Contact] OFF
